djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from leads import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.LandingView.as_view(), name="home"),
    path('leads/', include('leads.urls')),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', views.CustomLogoutView.as_view(), name="logout"),
    path('signup/', views.SignUpView.as_view(), name="signup")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('create/', views.LeadCreateView.as_view(), name='create'),
    path('<pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<pk>/update', views.LeadUpdateView.as_view(), name='update'),
    path('<pk>/delete', views.LeadDeleteView.as_view(), name='delete'),
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    pass


class Lead(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey("Agent", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

leads/forms.py
from django import forms
from .models import Lead
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model

User = get_user_model()


class CreateLeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            "first_name",
            "last_name",
            "age",
            "agent",
        )


class CreateLeadForm(forms.Form):
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    age = forms.IntegerField(min_value=1)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {"username": UsernameField}

leads/views.py
from django.shortcuts import render, redirect, reverse
from django.core.mail import send_mail
from django.contrib.auth.views import LogoutView
from .models import Lead
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
# from django.views.generic import TemplateView, ListView, DetailView
from .forms import CreateLeadModelForm, CreateLeadForm
from .forms import CustomUserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin


class LandingView(TemplateView):
    template_name = 'landing.html'


class CustomLogoutView(LogoutView):
    template_name = 'registration/logout.html'
    queryset = LogoutView


class SignUpView(CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreationForm
    context_object_name = 'form'

    def get_success_url(self):
        return reverse('login')


class LeadListView(ListView):
    template_name = "lead_list.html"
    queryset = Lead.objects.all()
    context_object_name = 'leads'


# def lead_list(request):
#     context = {
#         'leads': Lead.objects.all()
#     }
#     return render(request, 'lead_list.html', context)


# def home_page(request):
#     context = {
#         'leads': Lead.objects.all()
#     }
#     return render(request, 'homepage.html', context)


class LeadDetailView(DetailView):
    template_name = "lead-details.html"
    queryset = Lead.objects.all()
    context_object_name = "lead"


# def lead_detail(request, id):
#     context = {
#         'lead':  Lead.objects.get(id=id)
#     }
#     return render(request, 'lead-details.html', context)


# def lead_create(request):
#     if request.method == "POST":
#         form = CreateLeadModelForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('leads:list')
#     else:
#         form = CreateLeadModelForm()
#     context = {
#         "form": form
#     }
#     return render(request, "lead-create.html", context)
class LeadUpdateView(UpdateView):
    template_name = 'lead-update.html'
    queryset = Lead.objects.all()
    form_class = CreateLeadModelForm

    def get_success_url(self):
        return reverse('leads:list')


# def lead_update(request, id):
#     lead = Lead.objects.get(id=id)
#     form = CreateLeadModelForm(instance=lead)
#     if request.method == "POST":
#         form = CreateLeadModelForm(request.POST, instance=lead)
#         if form.is_valid():
#             form.save()
#             return redirect('leads:list')

#     context = {
#         "lead": lead,
#         "form": form
#     }
#     return render(request, 'lead-update.html', context)


class LeadDeleteView(DeleteView):
    queryset = queryset = Lead.objects.all()
    template_name = ""

    def get_success_url(self) -> str:
        return reverse("leads:list")


def lead_delete(request, id):
    lead = Lead.objects.get(id=id)
    lead.delete()
    return redirect('leads:list')

# def lead_update(request, id):
#     if request.method == "POST":
#         lead = Lead.objects.get(id=id)
#         form = CreateLeadForm(request.POST)
#         if form.is_valid():
#             lead.first_name = form.cleaned_data['first_name']
#             lead.last_name = form.cleaned_data['last_name']
#             lead.age = form.cleaned_data['age']
#             lead.save()
#             return redirect('leads:list')
#     else:
#         form = CreateLeadForm()

#     context = {
#         "form": form,
#         "lead": lead
#     }
#     return render(request, 'lead-update.html', context)


class LeadCreateView(LoginRequiredMixin, CreateView):
    template_name = 'lead-create.html'
    form_class = CreateLeadModelForm

    def get_success_url(self):
        return reverse('leads:list')

    def form_valid(self, form):
        send_mail(
            subject="New lead created",
            message="Please go to site to check detail of lead",
            from_email="test@test.com",
            recipient_list=["test2@test.com"]
        )
        return super(LeadCreateView, self).form_valid(form)

# def lead_create(request):
#     if request.method == "POST":
#         form = CreateLeadForm(request.POST)
#         if form.is_valid():
#             firstname = form.cleaned_data['first_name']
#             lastname = form.cleaned_data['last_name']
#             age = form.cleaned_data['age']
#             agent = Agent.objects.first()
#             Lead.objects.create(
#                 first_name=firstname,
#                 last_name=lastname,
#                 age=age,
#                 agent=agent,
#             )
#             return redirect('leads:list')
#     else:
#         form = CreateLeadForm()
#     context = {
#         "form": form
#     }
#     return render(request, "lead-create.html", context)

leads/templates/lead-create.html
{% extends 'base.html' %}

{% block content %}
<a href="/leads">Back to leads</a>
<h1>Create new lead</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>    
{% endblock content %}
    

leads/templates/lead-details.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
         
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">{{ lead.age }}</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Agent</span>
            <span class="ml-auto text-gray-900">{{ lead.agent }}</span>
          </div>
         
          <div class="flex gap-4 justify-end mt-5">
           
            <a href="{% url 'leads:update' lead.id %}" class="flex  text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Update</a>
            <a href="{% url 'leads:delete' lead.id %}" class="flex text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">Delete</a>
            
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>
<a href="/leads">Back to leads</a>
<h1>Lead Details of {{ lead.first_name }}</h1>

{{ lead.first_name }} has age {{ lead.age }}
agent: {{ lead.agent }}    
{% endblock content %}

leads/templates/lead-update.html
{% extends 'base.html' %}

{% block content %}
    <a href="/leads">Back to leads</a>
    <h1>Update lead {{ lead.first_name }} {{ lead.last_name }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>    
{% endblock content %}
    

leads/templates/lead_list.html
{% extends 'base.html' %}
{% block content %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
            <div class="flex w-full mb-20 justify-between items-center text-center">
                <h1 class="sm:text-3xl text-2xl font-medium title-fonttext-gray-900">Lead List</h1>
                <a href="{% url 'leads:create' %}" class="text-gray-600 hover:text-blue-500">Create new lead</a>
            </div>
            <div class="flex flex-wrap -m-4">
                {% for lead in leads %}
                <div class="xl:w-1/3 md:w-1/2 p-4">
                    <div class="border border-gray-200 p-6 rounded-lg">
                        <div class="w-10 h-10 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
                            <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                        </svg>
                        </div>
                        <h2 class="text-lg text-gray-900 font-medium title-font mb-2">{{ lead.first_name }}</h2>
                        <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waist co, subway tile poke farm.</p>

                        <div class="mt-5 text-right">
                            <a href="{% url 'leads:detail' lead.id %}">Details</a>
                        </div>
                    </div>
                </div>
                {% endfor %}            
            </div>       
        </div>
    </section>   
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>DJ CRM</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container mx-auto">
        {% include 'navbar.html' %}
        {% block content %}{% endblock content %}
    </div>

    {% include 'scripts.html' %}
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Home</h1>
    
</body>
</html>

templates/landing.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Microdosing synth tattooed vexillologist</h1>
        <p class="mb-8 leading-relaxed">Meggings kinfolk echo park stumptown DIY, kale chips beard jianbing tousled. Chambray dreamcatcher trust fund, kitsch vice godard disrupt ramps hexagon mustache umami snackwave tilde chillwave ugh. Pour-over meditation PBR&amp;B pickled ennui celiac mlkshk freegan photo booth af fingerstache pitchfork.</p>
        <div class="flex justify-center">
          <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
          <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button>
        </div>
      </div>
    </div>
  </section>    
{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a href="{% url 'home' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">DJ CRM</span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
            <a href="{% url 'leads:list' %}" class="mr-5 hover:text-gray-900">Leads</a>
        {% if not request.user.is_authenticated %}
            <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Sign up</a>
        {% endif %}
      </nav>        
      {% if request.user.is_authenticated %}
        <p>You are login as : {{ request.user.username }}</p>
        <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base ml-4 mt-4 md:mt-0">Logout
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </button>
        </form>
      {% else %}
      <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Login
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
      {% endif %}
    </div>
  </header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>